name: Generate Recipes Index

on:
  push:
    branches:
       - '**'
  workflow_dispatch:

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install fs-extra

    - name: Generate index
      run: |
        node .github/scripts/generate-index-recipes.js

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/recipes/index.json
        git commit -m "Update recipes index"
        git push origin main
