name: Slow Build, No Maven Cache

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build Lucee without using a Maven cache
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
    - name: Build Lucee with Maven
      run: ant -noinput -buildfile loader/build.xml quick
